"""Domain models. Import from here, not from the submodule."""

from app.models.domain import (
    DISCOVERED_VIA,
    NODE_STATES,
    Author,
    CandidateFeatures,
    CanonicalKey,
    CrawlState,
    Edge,
    FilterDecision,
    GraphNode,
    InteractionEvent,
    Outcome,
    Paper,
    PaperStub,
    PaperType,
    ScoredCandidate,
    VenueTier,
    normalize_title,
    strip_arxiv_version,
    surname_of,
)

__all__ = [
    "DISCOVERED_VIA",
    "NODE_STATES",
    "Author",
    "CandidateFeatures",
    "CanonicalKey",
    "CrawlState",
    "Edge",
    "FilterDecision",
    "GraphNode",
    "InteractionEvent",
    "Outcome",
    "Paper",
    "PaperStub",
    "PaperType",
    "ScoredCandidate",
    "VenueTier",
    "normalize_title",
    "strip_arxiv_version",
    "surname_of",
]
