/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions/{sid}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search S2 by title, annotated with what this session already knows.
         *
         *     An unknown title is an empty list, not an error -- "no such paper" is a
         *     valid answer to a search.
         */
        get: operations["search_api_sessions__sid__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Node
         * @description Add a paper to this session's graph as a SEED at depth 0.
         */
        post: operations["add_node_api_sessions__sid__nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/nodes/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Detail
         * @description Full metadata plus this session's view of one node.
         */
        get: operations["get_node_detail_api_sessions__sid__nodes__paper_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Node
         * @description Remove one node, and whatever it was the only justification for (R2.6).
         *
         *     `dry_run` defaults to **true**: the safe reading of an omitted parameter is
         *     the one that does not destroy anything. The preview runs the identical
         *     computation inside a rolled-back transaction, so its count is what actually
         *     happens rather than a second implementation free to disagree.
         *
         *     Removal takes graph membership only. The paper and its edges stay in the
         *     corpus, still coupling everything that cites them.
         */
        delete: operations["delete_node_api_sessions__sid__nodes__paper_id__delete"];
        options?: never;
        head?: never;
        /**
         * Label Node
         * @description Change one paper's label (R2.2).
         *
         *     One endpoint rather than `/like` + `/dislike` + `/unlike`: PLAN.md wants
         *     "one state machine, one validation path, one audit write", and three
         *     endpoints would be three places to forget the event that
         *     `scripts/rebuild_state.py` rebuilds from.
         *
         *     The two refusals mean different things. A paper with no node here is a 404
         *     -- boundary papers are in the corpus by design and have no state to change.
         *     A transition the machine forbids is a 409 carrying its `error_code`,
         *     because "you cannot do that" is not actionable while `SEED_NOT_LABELABLE`
         *     names a rule the UI can explain.
         */
        patch: operations["label_node_api_sessions__sid__nodes__paper_id__patch"];
        trace?: never;
    };
    "/api/sessions/{sid}/nodes/{paper_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore
         * @description Bring a tombstoned paper back (R2.8).
         *
         *     The only path back, and never automatic -- expansion must not rediscover
         *     something you removed on purpose. It returns as CANDIDATE rather than to
         *     whatever label it had: that label was part of a judgment you reversed by
         *     removing it, and restoring it silently would put words in your mouth.
         */
        post: operations["restore_api_sessions__sid__nodes__paper_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description This session's graph: every node, every edge between them, and meta.
         */
        get: operations["get_graph_api_sessions__sid__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Positions
         * @description Persist the current arrangement (R2.12).
         *
         *     PLAN.md M6 calls layout instability the thing that "kills usability", and
         *     the `pos_x`/`pos_y` columns have been in the schema since migration 0001
         *     with nothing ever writing one -- so every reload threw away whatever the
         *     user had arranged. This is the missing half.
         *
         *     **PUT, and bulk.** The client calls it after every settled layout and after
         *     dragging stops, so it has to be safely repeatable; and a 200-node graph
         *     settling is one event, not two hundred.
         *
         *     **A paper with no node here is skipped rather than refused.** A node can be
         *     removed between the layout settling and this request landing. That is a
         *     race, and failing the whole request over it would discard an arrangement
         *     that is still correct for everything else. The `saved` count is what keeps
         *     the skip visible instead of silent.
         */
        put: operations["save_positions_api_sessions__sid__positions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description What is actually in this session's graph (R2.13).
         *
         *     A server endpoint rather than arithmetic in the panel, because BUILD.md's
         *     verification is "counts match the DB". `GET /graph` can be filtered by
         *     state, and a panel totalling a filtered response would confidently report a
         *     subset as the whole -- a failure whose symptom is that everything looks
         *     fine.
         */
        get: operations["get_stats_api_sessions__sid__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description What the graph is not showing you, and why (R2.14).
         *
         *     PLAN.md M5: "A filter you cannot audit is a filter you cannot tune, and you
         *     will silently discard good papers for weeks without noticing."
         */
        get: operations["get_review_api_sessions__sid__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/expansions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Expansion
         * @description Queue an expansion and answer with the id to poll.
         */
        post: operations["create_expansion_api_sessions__sid__expansions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/expansions/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expansion
         * @description One job's status, stage and counters. Poll this about once a second.
         */
        get: operations["get_expansion_api_sessions__sid__expansions__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Is the database reachable, is S2 configured, how much is cached, and
         *     how big is the graph.
         *
         *     Never raises: an endpoint that 500s when the database is down tells you
         *     nothing a timeout would not.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddNodeRequest
         * @description Add one paper to a session's graph.
         */
        AddNodeRequest: {
            /** S2 Paper Id */
            s2_paper_id: string;
            /**
             * Force
             * @description Admit the paper even if the filter cascade rejects it. The rejection is still recorded -- an override is never silent.
             * @default false
             */
            force: boolean;
        };
        /**
         * ExpandRequest
         * @description One expansion's parameters. Every field optional; the defaults expand.
         */
        ExpandRequest: {
            /**
             * Hops
             * @default 1
             * @constant
             */
            hops: 1;
            /**
             * Max New
             * @default 20
             */
            max_new: number;
            /**
             * Api Call Budget
             * @default 60
             */
            api_call_budget: number;
            /**
             * Max Nodes
             * @default 2000
             */
            max_nodes: number;
        };
        /**
         * ExpandResponse
         * @description What the run actually did.
         */
        ExpandResponse: {
            /**
             * N Pool
             * @description Candidates pooled before ranking.
             */
            n_pool: number;
            /** N Added */
            n_added: number;
            /**
             * Added Paper Ids
             * @description Papers admitted by this run, sorted. Usable against GET /graph.
             */
            added_paper_ids?: number[];
            /**
             * Boundary
             * @description Papers stored with their edges but denied a node. Should be a large fraction on a backward pass; zero means the year floor has started deleting evidence rather than withholding recommendations.
             */
            boundary: number;
            /**
             * Backward Fetched
             * @default 0
             */
            backward_fetched: number;
            /**
             * Forward Fetched
             * @default 0
             */
            forward_fetched: number;
            /**
             * Hub Skipped
             * @description Papers too heavily cited to expand forward from.
             * @default 0
             */
            hub_skipped: number;
            /**
             * Api Calls
             * @default 0
             */
            api_calls: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Error
             * @description Why the run stopped early, if it did. Not a failure -- the result is still committed and the status is still 200.
             */
            error?: string | null;
        };
        /**
         * GraphEdgeOut
         * @description One drawn edge, always citing -> cited.
         */
        GraphEdgeOut: {
            /** Source */
            source: number;
            /** Target */
            target: number;
            /**
             * Is Influential
             * @default false
             */
            is_influential: boolean;
        };
        /**
         * GraphMeta
         * @description What the client needs to caveat what it is showing.
         */
        GraphMeta: {
            /** Node Count */
            node_count: number;
            /** Edge Count */
            edge_count: number;
            /** Config Version */
            config_version: string;
            /**
             * Crawl Completeness
             * @description |non-stub| / |nodes|. PLAN.md section I: PageRank over a partially crawled graph is biased, so R3 suppresses that column below 0.6.
             */
            crawl_completeness: number;
        };
        /**
         * GraphNodeOut
         * @description One drawn node.
         */
        GraphNodeOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Score */
            score?: number | null;
            /** Year */
            year?: number | null;
            /** Citation Count */
            citation_count?: number | null;
            /** Paper Type */
            paper_type?: string | null;
            /**
             * In Degree
             * @default 0
             */
            in_degree: number;
            /**
             * Out Degree
             * @default 0
             */
            out_degree: number;
            pos?: components["schemas"]["Position"] | null;
        };
        /**
         * GraphResponse
         * @description The whole graph. Not paginated -- see the router's docstring.
         */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            meta: components["schemas"]["GraphMeta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Four things worth knowing at 2am, not `{"status": "ok"}`.
         */
        HealthResponse: {
            /**
             * Db
             * @description "ok", or "error: <ExceptionType>" if unreachable.
             */
            db: string;
            /**
             * S2 Reachable
             * @description "configured" or "no_api_key". Deliberately not a live probe -- a monitoring loop that costs an upstream request becomes a rate-limit problem, and at one request per second that is the entire budget.
             */
            s2_reachable: string;
            /** Cache Rows */
            cache_rows: number;
            /**
             * Node Count
             * @description Nodes in the configured session, not globally.
             */
            node_count: number;
            /** Session Id */
            session_id: number;
            /**
             * Config Version
             * @description Which filter config produced this graph. The first question when it looks odd.
             */
            config_version: string;
        };
        /**
         * JobAccepted
         * @description The 202 body (R2.4).
         *
         *     Just the id and where to look. The work has not started, so there is
         *     nothing else true to say yet, and inventing an optimistic count here would
         *     be a number the poll then contradicts.
         */
        JobAccepted: {
            /** Job Id */
            job_id: number;
            /** Session Id */
            session_id: number;
            /**
             * Status
             * @default QUEUED
             */
            status: string;
            /**
             * Poll
             * @description Where to poll for this job's progress.
             */
            poll: string;
        };
        /**
         * JobProgress
         * @description Counters as far as the run has got.
         *
         *     Every field is optional because they genuinely are unknown until the stage
         *     that produces them completes -- and `null` is the honest way to say "not
         *     yet", where a 0 would read as "none found".
         */
        JobProgress: {
            /**
             * Pool
             * @description Candidates pooled. Null until pooling.
             */
            pool?: number | null;
            /**
             * Filtered
             * @description Boundary papers stored without a node. Null until fetching ends.
             */
            filtered?: number | null;
            /**
             * Added
             * @description Nodes admitted. Null until ranking ends.
             */
            added?: number | null;
            /** Api Calls */
            api_calls?: number | null;
            /** Cache Hits */
            cache_hits?: number | null;
        };
        /**
         * JobStatus
         * @description What `GET /expansions/{id}` returns -- PLAN.md's `{status, stage, progress}`.
         *
         *     `stage` is derived from the counters rather than stored: a stored stage is
         *     a second place for the truth to live, and it is the copy that goes stale
         *     when a process dies mid-run.
         *
         *     `result` is present only once the job is DONE, and carries exactly what the
         *     synchronous R1.18 response carried. The client needs `added_paper_ids` to
         *     update the graph, and making it fetch the whole graph again to discover
         *     three new nodes would undo the point of reporting them at all.
         */
        JobStatus: {
            /** Job Id */
            job_id: number;
            /** Session Id */
            session_id: number;
            /**
             * Status
             * @description QUEUED | RUNNING | DONE | FAILED | CANCELLED.
             */
            status: string;
            /**
             * Stage
             * @description QUEUED | FETCHING | POOLING | RANKING | ADDING | DONE | ...
             */
            stage: string;
            progress: components["schemas"]["JobProgress"];
            /**
             * Error
             * @description Why the run stopped early, or why it failed. A DONE job with an error was truncated, not broken -- a partial expansion is a success.
             */
            error?: string | null;
            /** @description Present once status is DONE. */
            result?: components["schemas"]["ExpandResponse"] | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * LabelRequest
         * @description Change one paper's label (R2.2).
         *
         *     One endpoint, not `/like` + `/dislike` + `/unlike`. PLAN.md: "One state
         *     machine, one validation path, one audit write." Three endpoints means three
         *     places to forget the event, and the event log is what
         *     `scripts/rebuild_state.py` reconstructs the graph from.
         */
        LabelRequest: {
            /**
             * State
             * @description Target state. SEED is accepted by the schema and refused by the state machine with CANNOT_PROMOTE_TO_SEED -- a 409 that names the rule is more useful than a 422 that says the value is not in an enum, because the caller's mistake is about meaning, not typing.
             * @enum {string}
             */
            state: "CANDIDATE" | "LIKED" | "DISLIKED" | "SEED";
        };
        /**
         * LabelResponse
         * @description BUILD.md: 200 returns `{node, rescored_count}`.
         */
        LabelResponse: {
            node: components["schemas"]["NodeResponse"];
            /**
             * Swept
             * @description Papers the sweep collected as a consequence of this label change. Non-empty only when the change cost the graph an anchor. Without it the response would describe one node while the client's picture of the rest of the graph silently went stale.
             */
            swept?: number[];
            /**
             * Rescored Count
             * @description Nodes whose score changed as a result. Always 0 until R3 ships ranking -- reported now so the contract does not change shape when it starts being non-zero.
             * @default 0
             */
            rescored_count: number;
        };
        /**
         * NodeDetail
         * @description Everything R1.22's `<NodeInspector>` renders.
         *
         *     Two kinds of fact, deliberately in one response because the panel shows
         *     them together:
         *
         *         global      title, authors, venue, date, citations, type, categories
         *         per-session state, depth, score, features, score_breakdown, degrees
         *
         *     The abstract is **not** here. CLAUDE.md is explicit that abstracts are
         *     stored for embeddings only; shipping one per inspector click spends bytes
         *     on something the design says is not for reading, and no LLM stage consumes
         *     it.
         */
        NodeDetail: {
            /** Paper Id */
            paper_id: number;
            /** S2 Paper Id */
            s2_paper_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string[];
            /** Venue */
            venue?: string | null;
            /** Year */
            year?: number | null;
            /** Publication Date */
            publication_date?: string | null;
            /** Doi */
            doi?: string | null;
            /** Arxiv Id */
            arxiv_id?: string | null;
            /**
             * Citation Count
             * @default 0
             */
            citation_count: number;
            /**
             * Reference Count
             * @default 0
             */
            reference_count: number;
            /**
             * Influential Citation Count
             * @default 0
             */
            influential_citation_count: number;
            /** Paper Type */
            paper_type?: string | null;
            /** Primary Arxiv Category */
            primary_arxiv_category?: string | null;
            /** Arxiv Categories */
            arxiv_categories?: string[];
            /** Crawl State */
            crawl_state: string;
            /** State */
            state: string;
            /** Depth */
            depth: number;
            /** Score */
            score?: number | null;
            /**
             * In Degree
             * @default 0
             */
            in_degree: number;
            /**
             * Out Degree
             * @default 0
             */
            out_degree: number;
            /** Features */
            features?: {
                [key: string]: unknown;
            };
            /**
             * Score Breakdown
             * @description Per-term contributions to the score. Empty until R3 ships real features -- present-and-empty so the UI renders 'unavailable' from the shape rather than from a special case.
             */
            score_breakdown?: {
                [key: string]: unknown;
            };
        };
        /**
         * NodePosition
         * @description Where one node sits, as the client laid it out (R2.12).
         */
        NodePosition: {
            /** Paper Id */
            paper_id: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * NodeResponse
         * @description A node as the graph holds it, plus the title so the UI can render it.
         */
        NodeResponse: {
            /** Session Id */
            session_id: number;
            /** Paper Id */
            paper_id: number;
            /** State */
            state: string;
            /** Depth */
            depth: number;
            /** Title */
            title: string;
            /** Score */
            score?: number | null;
            /** Year */
            year?: number | null;
        };
        /**
         * Position
         * @description A laid-out position, in Cytoscape's coordinate space.
         */
        Position: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * ReasonCount
         * @description How many papers one reason accounts for. Largest first.
         */
        ReasonCount: {
            /** Reason Code */
            reason_code: string;
            /** Count */
            count: number;
        };
        /**
         * RejectedResponse
         * @description The 422 body, wrapped in FastAPI's standard error envelope.
         *
         *     The nesting is deliberate rather than incidental. FastAPI puts every
         *     `HTTPException` payload under `detail`, so the 404, 409 and 503 from this
         *     same endpoint all arrive as `{"detail": ...}`. Flattening only the 422
         *     would give the frontend one error shape to special-case, and would make
         *     this declared model disagree with what the endpoint actually emits -- which
         *     matters more than usual here, because `make types` generates the
         *     frontend's error handling from it.
         */
        RejectedResponse: {
            detail: components["schemas"]["RejectionDetail"];
        };
        /**
         * RejectionDetail
         * @description Why the cascade refused a paper.
         *
         *     `reason_code` is the point of it: "rejected" is not actionable, "PRE_ERA"
         *     names the rule and lets the UI offer `force` against something the user can
         *     read and disagree with.
         */
        RejectionDetail: {
            /** Detail */
            detail: string;
            /** Reason Code */
            reason_code: string;
            /** Stage */
            stage: string;
        };
        /**
         * RemovalCandidate
         * @description One paper a removal would take. Named, not merely counted.
         */
        RemovalCandidate: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /**
         * RemovalPreview
         * @description `dry_run=true`. PLAN.md marks this the call you always make first.
         */
        RemovalPreview: {
            /** Would Remove */
            would_remove: components["schemas"]["RemovalCandidate"][];
            /** Count */
            count: number;
        };
        /**
         * RemovalResult
         * @description `dry_run=false`.
         *
         *     `removed` and `gc_swept` stay separate because two different things
         *     happened: you removed one paper, and the system collected others as a
         *     consequence. One merged list would hide which was your decision, and
         *     R2.14's drawer groups by exactly that distinction.
         */
        RemovalResult: {
            /** Removed */
            removed: number[];
            /** Gc Swept */
            gc_swept: number[];
        };
        /**
         * ReviewBucketOut
         * @description One tab.
         *
         *     `total` and `by_reason` are complete; `papers` is a capped sample. A mature
         *     corpus rejects thousands of papers, and materialising all of them to render
         *     a drawer would make this slowest exactly when the graph is interesting.
         */
        ReviewBucketOut: {
            /** Total */
            total: number;
            /** By Reason */
            by_reason?: components["schemas"]["ReasonCount"][];
            /** Papers */
            papers?: components["schemas"]["ReviewPaperOut"][];
            /**
             * Truncated
             * @description True when `papers` is a sample of `total`. Stated rather than left for the client to infer from a suspiciously round number.
             * @default false
             */
            truncated: boolean;
        };
        /**
         * ReviewPaperOut
         * @description One row of the review drawer (R2.14).
         */
        ReviewPaperOut: {
            /** Paper Id */
            paper_id: number;
            /** Title */
            title: string;
            /**
             * Reason Code
             * @description Why it is absent. A filter reason for the Quarantined and Rejected tabs; the event type (REMOVED | GC_SWEPT) for Removed.
             */
            reason_code: string;
            /**
             * Stage
             * @description Which filter stage decided, or for a removal the actor -- USER for a removal you asked for, SYSTEM for one the sweep drew from it.
             */
            stage: string;
            /** Year */
            year?: number | null;
        };
        /**
         * ReviewResponse
         * @description The three tabs, always all three (R2.14).
         *
         *     Three different kinds of absence. Quarantine is "probably applied ML but I
         *     am not sure", which PLAN.md notes is most of the hard cases -- folding it
         *     into Rejected would bury exactly the papers most worth a human glance.
         */
        ReviewResponse: {
            quarantined: components["schemas"]["ReviewBucketOut"];
            rejected: components["schemas"]["ReviewBucketOut"];
            removed: components["schemas"]["ReviewBucketOut"];
        };
        /**
         * SavePositionsRequest
         * @description A whole arrangement in one request (R2.12).
         *
         *     Bulk because a settled layout is one event: a 200-node graph sent one node
         *     at a time would be 200 transactions describing a single act.
         *
         *     The cap is `max_nodes` with room to spare. A graph cannot exceed that, so a
         *     larger list is either a bug or something not worth writing.
         */
        SavePositionsRequest: {
            /** Positions */
            positions?: components["schemas"]["NodePosition"][];
        };
        /**
         * SavePositionsResponse
         * @description How many rows were actually written.
         */
        SavePositionsResponse: {
            /**
             * Saved
             * @description Rows updated. Lower than what was sent when a node was removed between the layout settling and this request landing -- a race, not an error, but one worth being able to see.
             */
            saved: number;
        };
        /**
         * SearchHit
         * @description One search result, annotated with this session's history of it.
         */
        SearchHit: {
            /** S2 Paper Id */
            s2_paper_id: string;
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
            /** Citation Count */
            citation_count?: number | null;
            /** Venue */
            venue?: string | null;
            /** Authors */
            authors?: string[];
            /**
             * Already In Graph
             * @description This paper has a node in the current session's graph.
             * @default false
             */
            already_in_graph: boolean;
            /**
             * Previously Removed
             * @description The paper's latest event in this session is a tombstone -- it was in the graph and was removed. Derived, not stored, so a restore lifts it.
             * @default false
             */
            previously_removed: boolean;
        };
        /**
         * StatsResponse
         * @description `<StatsPanel>` v1 (R2.13).
         *
         *     Deliberately no `pagerank`. BUILD.md defers it to R3, and a field that
         *     exists and is always null invites a panel to render an empty row for a
         *     metric nobody has computed -- the shape should say what is available.
         */
        StatsResponse: {
            /** Node Count */
            node_count: number;
            /**
             * Edge Count
             * @description Edges with both endpoints in this graph. An edge into a boundary paper is real and structurally useful, but the panel sits beside a picture that does not draw it.
             */
            edge_count: number;
            /**
             * By State
             * @description Every state, including the ones at zero, so a row is never missing.
             */
            by_state: {
                [key: string]: number;
            };
            /**
             * Components
             * @description Connected pieces of the undirected projection.
             */
            components: number;
            /**
             * Avg Degree
             * @description 2E/N -- each edge counts at both of its endpoints.
             */
            avg_degree: number;
            /**
             * Density
             * @description 2E / (N(N-1)), against the undirected maximum. Bounded here on purpose: a density above 1.0 is arithmetically impossible, so if one is ever computed it means the edge count and the node count came from different reads -- and a loud 500 beats shipping an absurd number to a panel nobody would think to doubt.
             */
            density: number;
            /**
             * Crawl Completeness
             * @description |non-stub| / |nodes|. PLAN.md section I: PageRank over a partially crawled graph is biased, and R3 suppresses that column below 0.6.
             */
            crawl_completeness: number;
        };
        /**
         * TransitionRefusedDetail
         * @description Why the state machine refused, in the shape the UI branches on.
         */
        TransitionRefusedDetail: {
            /** Detail */
            detail: string;
            /** Error Code */
            error_code: string;
            /** From State */
            from_state: string;
            /** To State */
            to_state: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_api_sessions__sid__search_get: {
        parameters: {
            query: {
                /** @description Paper title to search for. */
                q: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_node_api_sessions__sid__nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectedResponse"];
                };
            };
        };
    };
    get_node_detail_api_sessions__sid__nodes__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Local paper id. */
                paper_id: number;
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_node_api_sessions__sid__nodes__paper_id__delete: {
        parameters: {
            query?: {
                /** @description Preview only. Defaults to true -- PLAN.md: always call first. */
                dry_run?: boolean;
            };
            header?: never;
            path: {
                /** @description Local paper id. */
                paper_id: number;
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemovalPreview"] | components["schemas"]["RemovalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_node_api_sessions__sid__nodes__paper_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Local paper id. */
                paper_id: number;
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionRefusedDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_sessions__sid__nodes__paper_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Local paper id. */
                paper_id: number;
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_sessions__sid__graph_get: {
        parameters: {
            query?: {
                /** @description Comma-separated states to include, e.g. `SEED,LIKED`. */
                states?: string | null;
            };
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_positions_api_sessions__sid__positions_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePositionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavePositionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_sessions__sid__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_sessions__sid__review_get: {
        parameters: {
            query?: {
                /** @description Rows per tab. Counts stay complete regardless. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expansion_api_sessions__sid__expansions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExpandRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expansion_api_sessions__sid__expansions__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id returned by the 202. */
                job_id: number;
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
