/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions/{sid}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search S2 by title, annotated with what this session already knows.
         *
         *     An unknown title is an empty list, not an error -- "no such paper" is a
         *     valid answer to a search.
         */
        get: operations["search_api_sessions__sid__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Node
         * @description Add a paper to this session's graph as a SEED at depth 0.
         */
        post: operations["add_node_api_sessions__sid__nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/nodes/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Detail
         * @description Full metadata plus this session's view of one node.
         */
        get: operations["get_node_detail_api_sessions__sid__nodes__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description This session's graph: every node, every edge between them, and meta.
         */
        get: operations["get_graph_api_sessions__sid__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sid}/expansions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Expansion
         * @description Expand this session's graph by one hop and return what the run did.
         */
        post: operations["create_expansion_api_sessions__sid__expansions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Is the database reachable, is S2 configured, how much is cached, and
         *     how big is the graph.
         *
         *     Never raises: an endpoint that 500s when the database is down tells you
         *     nothing a timeout would not.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddNodeRequest
         * @description Add one paper to a session's graph.
         */
        AddNodeRequest: {
            /** S2 Paper Id */
            s2_paper_id: string;
            /**
             * As State
             * @default SEED
             * @constant
             */
            as_state: "SEED";
            /**
             * Force
             * @description Admit the paper even if the filter cascade rejects it. The rejection is still recorded -- an override is never silent.
             * @default false
             */
            force: boolean;
        };
        /**
         * ExpandRequest
         * @description One expansion's parameters. Every field optional; the defaults expand.
         */
        ExpandRequest: {
            /**
             * Hops
             * @default 1
             * @constant
             */
            hops: 1;
            /**
             * Max New
             * @default 20
             */
            max_new: number;
            /**
             * Api Call Budget
             * @default 60
             */
            api_call_budget: number;
            /**
             * Max Nodes
             * @default 2000
             */
            max_nodes: number;
        };
        /**
         * ExpandResponse
         * @description What the run actually did.
         */
        ExpandResponse: {
            /**
             * N Pool
             * @description Candidates pooled before ranking.
             */
            n_pool: number;
            /** N Added */
            n_added: number;
            /**
             * Added Paper Ids
             * @description Papers admitted by this run, sorted. Usable against GET /graph.
             */
            added_paper_ids?: number[];
            /**
             * Boundary
             * @description Papers stored with their edges but denied a node. Should be a large fraction on a backward pass; zero means the year floor has started deleting evidence rather than withholding recommendations.
             */
            boundary: number;
            /**
             * Backward Fetched
             * @default 0
             */
            backward_fetched: number;
            /**
             * Forward Fetched
             * @default 0
             */
            forward_fetched: number;
            /**
             * Hub Skipped
             * @description Papers too heavily cited to expand forward from.
             * @default 0
             */
            hub_skipped: number;
            /**
             * Api Calls
             * @default 0
             */
            api_calls: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Error
             * @description Why the run stopped early, if it did. Not a failure -- the result is still committed and the status is still 200.
             */
            error?: string | null;
        };
        /**
         * GraphEdgeOut
         * @description One drawn edge, always citing -> cited.
         */
        GraphEdgeOut: {
            /** Source */
            source: number;
            /** Target */
            target: number;
            /**
             * Is Influential
             * @default false
             */
            is_influential: boolean;
        };
        /**
         * GraphMeta
         * @description What the client needs to caveat what it is showing.
         */
        GraphMeta: {
            /** Node Count */
            node_count: number;
            /** Edge Count */
            edge_count: number;
            /** Config Version */
            config_version: string;
            /**
             * Crawl Completeness
             * @description |non-stub| / |nodes|. PLAN.md section I: PageRank over a partially crawled graph is biased, so R3 suppresses that column below 0.6.
             */
            crawl_completeness: number;
        };
        /**
         * GraphNodeOut
         * @description One drawn node.
         */
        GraphNodeOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Score */
            score?: number | null;
            /** Year */
            year?: number | null;
            /** Citation Count */
            citation_count?: number | null;
            /** Paper Type */
            paper_type?: string | null;
            /**
             * In Degree
             * @default 0
             */
            in_degree: number;
            /**
             * Out Degree
             * @default 0
             */
            out_degree: number;
            pos?: components["schemas"]["Position"] | null;
        };
        /**
         * GraphResponse
         * @description The whole graph. Not paginated -- see the router's docstring.
         */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            meta: components["schemas"]["GraphMeta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Four things worth knowing at 2am, not `{"status": "ok"}`.
         */
        HealthResponse: {
            /**
             * Db
             * @description "ok", or "error: <ExceptionType>" if unreachable.
             */
            db: string;
            /**
             * S2 Reachable
             * @description "configured" or "no_api_key". Deliberately not a live probe -- a monitoring loop that costs an upstream request becomes a rate-limit problem, and at one request per second that is the entire budget.
             */
            s2_reachable: string;
            /** Cache Rows */
            cache_rows: number;
            /**
             * Node Count
             * @description Nodes in the configured session, not globally.
             */
            node_count: number;
            /** Session Id */
            session_id: number;
            /**
             * Config Version
             * @description Which filter config produced this graph. The first question when it looks odd.
             */
            config_version: string;
        };
        /**
         * NodeDetail
         * @description Everything R1.22's `<NodeInspector>` renders.
         *
         *     Two kinds of fact, deliberately in one response because the panel shows
         *     them together:
         *
         *         global      title, authors, venue, date, citations, type, categories
         *         per-session state, depth, score, features, score_breakdown, degrees
         *
         *     The abstract is **not** here. CLAUDE.md is explicit that abstracts are
         *     stored for embeddings only; shipping one per inspector click spends bytes
         *     on something the design says is not for reading, and no LLM stage consumes
         *     it.
         */
        NodeDetail: {
            /** Paper Id */
            paper_id: number;
            /** S2 Paper Id */
            s2_paper_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string[];
            /** Venue */
            venue?: string | null;
            /** Year */
            year?: number | null;
            /** Publication Date */
            publication_date?: string | null;
            /** Doi */
            doi?: string | null;
            /** Arxiv Id */
            arxiv_id?: string | null;
            /**
             * Citation Count
             * @default 0
             */
            citation_count: number;
            /**
             * Reference Count
             * @default 0
             */
            reference_count: number;
            /**
             * Influential Citation Count
             * @default 0
             */
            influential_citation_count: number;
            /** Paper Type */
            paper_type?: string | null;
            /** Primary Arxiv Category */
            primary_arxiv_category?: string | null;
            /** Arxiv Categories */
            arxiv_categories?: string[];
            /** Crawl State */
            crawl_state: string;
            /** State */
            state: string;
            /** Depth */
            depth: number;
            /** Score */
            score?: number | null;
            /**
             * In Degree
             * @default 0
             */
            in_degree: number;
            /**
             * Out Degree
             * @default 0
             */
            out_degree: number;
            /** Features */
            features?: {
                [key: string]: unknown;
            };
            /**
             * Score Breakdown
             * @description Per-term contributions to the score. Empty until R3 ships real features -- present-and-empty so the UI renders 'unavailable' from the shape rather than from a special case.
             */
            score_breakdown?: {
                [key: string]: unknown;
            };
        };
        /**
         * NodeResponse
         * @description A node as the graph holds it, plus the title so the UI can render it.
         */
        NodeResponse: {
            /** Session Id */
            session_id: number;
            /** Paper Id */
            paper_id: number;
            /** State */
            state: string;
            /** Depth */
            depth: number;
            /** Title */
            title: string;
            /** Score */
            score?: number | null;
            /** Year */
            year?: number | null;
        };
        /**
         * Position
         * @description A laid-out position, in Cytoscape's coordinate space.
         */
        Position: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * RejectedResponse
         * @description The 422 body, wrapped in FastAPI's standard error envelope.
         *
         *     The nesting is deliberate rather than incidental. FastAPI puts every
         *     `HTTPException` payload under `detail`, so the 404, 409 and 503 from this
         *     same endpoint all arrive as `{"detail": ...}`. Flattening only the 422
         *     would give the frontend one error shape to special-case, and would make
         *     this declared model disagree with what the endpoint actually emits -- which
         *     matters more than usual here, because `make types` generates the
         *     frontend's error handling from it.
         */
        RejectedResponse: {
            detail: components["schemas"]["RejectionDetail"];
        };
        /**
         * RejectionDetail
         * @description Why the cascade refused a paper.
         *
         *     `reason_code` is the point of it: "rejected" is not actionable, "PRE_ERA"
         *     names the rule and lets the UI offer `force` against something the user can
         *     read and disagree with.
         */
        RejectionDetail: {
            /** Detail */
            detail: string;
            /** Reason Code */
            reason_code: string;
            /** Stage */
            stage: string;
        };
        /**
         * SearchHit
         * @description One search result, annotated with this session's history of it.
         */
        SearchHit: {
            /** S2 Paper Id */
            s2_paper_id: string;
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
            /** Citation Count */
            citation_count?: number | null;
            /** Venue */
            venue?: string | null;
            /** Authors */
            authors?: string[];
            /**
             * Already In Graph
             * @description This paper has a node in the current session's graph.
             * @default false
             */
            already_in_graph: boolean;
            /**
             * Previously Removed
             * @description The paper's latest event in this session is a tombstone -- it was in the graph and was removed. Derived, not stored, so a restore lifts it.
             * @default false
             */
            previously_removed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_api_sessions__sid__search_get: {
        parameters: {
            query: {
                /** @description Paper title to search for. */
                q: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_node_api_sessions__sid__nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectedResponse"];
                };
            };
        };
    };
    get_node_detail_api_sessions__sid__nodes__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Local paper id. */
                paper_id: number;
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_sessions__sid__graph_get: {
        parameters: {
            query?: {
                /** @description Comma-separated states to include, e.g. `SEED,LIKED`. */
                states?: string | null;
            };
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expansion_api_sessions__sid__expansions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id. */
                sid: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExpandRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
